---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: openshift
  namespace: {{ .Values.namespace }}
spec:
  image: {{ .Values.image }}
  transport: streamable-http
  mcpPort: 8000
  proxyPort: 8080
  podTemplateSpec:
    spec:
      containers:
      - name: mcp
        args:
        - --port
        - "8000"
        command:
        - ./kubernetes-mcp-server
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
